[package]
name = "rust_learn"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vec"
path = "src/collections/vec.rs"

[[bin]]
name = "vecdeque"
path = "src/collections/vecdeque.rs"

[[bin]]
name = "linkedlist"
path = "src/collections/linkedlist.rs"

[[bin]]
name = "box_array"
path = "src/collections/box_array.rs"

[[bin]]
name = "btreemap"
path = "src/collections/btreemap.rs"

[[bin]]
name = "hashmap"
path = "src/collections/hashmap.rs"

[[bin]]
name = "hashset"
path = "src/collections/hashset.rs"

[[bin]]
name = "btreeset"
path = "src/collections/btreeset.rs"

[[bin]]
name = "basic_thread"
path = "src/threads/basic.rs"

[[bin]]
name = "thread_local"
path = "src/threads/thread_local.rs"

[[bin]]
name = "thread_sync"
path = "src/threads/sync.rs"

[[bin]]
name = "thread_attributes"
path = "src/threads/attributes.rs"

[[bin]]
name = "thread_advanced"
path = "src/threads/advanced.rs"

[[bin]]
name = "thread_complete"
path = "src/threads/complete.rs"

[[bin]]
name = "01_variables_variables1"
path = "src/exercises/01_variables/variables1.rs"

[[bin]]
name = "01_variables_variables2"
path = "src/exercises/01_variables/variables2.rs"

[[bin]]
name = "01_variables_variables3"
path = "src/exercises/01_variables/variables3.rs"

[[bin]]
name = "01_variables_variables4"
path = "src/exercises/01_variables/variables4.rs"

[[bin]]
name = "01_variables_variables5"
path = "src/exercises/01_variables/variables5.rs"

[[bin]]
name = "01_variables_variables6"
path = "src/exercises/01_variables/variables6.rs"

[[bin]]
name = "02_functions_functions1"
path = "src/exercises/02_functions/functions1.rs"

[[bin]]
name = "02_functions_functions2"
path = "src/exercises/02_functions/functions2.rs"

[[bin]]
name = "02_functions_functions3"
path = "src/exercises/02_functions/functions3.rs"

[[bin]]
name = "02_functions_functions4"
path = "src/exercises/02_functions/functions4.rs"

[[bin]]
name = "02_functions_functions5"
path = "src/exercises/02_functions/functions5.rs"

[[bin]]
name = "03_if_if1"
path = "src/exercises/03_if/if1.rs"

[[bin]]
name = "03_if_if2"
path = "src/exercises/03_if/if2.rs"

[[bin]]
name = "03_if_if3"
path = "src/exercises/03_if/if3.rs"

[[bin]]
name = "04_primitive_type_primitive_types1"
path = "src/exercises/04_primitive_types/primitive_types1.rs"

[[bin]]
name = "04_primitive_type_primitive_types2"
path = "src/exercises/04_primitive_types/primitive_types2.rs"

[[bin]]
name = "04_primitive_type_primitive_types3"
path = "src/exercises/04_primitive_types/primitive_types3.rs"

[[bin]]
name = "04_primitive_type_primitive_types4"
path = "src/exercises/04_primitive_types/primitive_types4.rs"

[[bin]]
name = "04_primitive_type_primitive_types5"
path = "src/exercises/04_primitive_types/primitive_types5.rs"

[[bin]]
name = "04_primitive_type_primitive_types6"
path = "src/exercises/04_primitive_types/primitive_types6.rs"

[[bin]]
name = "05_vecs_vecs1"
path = "src/exercises/05_vecs/vecs1.rs"

[[bin]]
name = "05_vecs_vecs2"
path = "src/exercises/05_vecs/vecs2.rs"

[[bin]]
name = "06_move_semantics_move_semantics1"
path = "src/exercises/06_move_semantics/move_semantics1.rs"

[[bin]]
name = "06_move_semantics_move_semantics2"
path = "src/exercises/06_move_semantics/move_semantics2.rs"

[[bin]]
name = "06_move_semantics_move_semantics3"
path = "src/exercises/06_move_semantics/move_semantics3.rs"

[[bin]]
name = "06_move_semantics_move_semantics4"
path = "src/exercises/06_move_semantics/move_semantics4.rs"

[[bin]]
name = "06_move_semantics_move_semantics5"
path = "src/exercises/06_move_semantics/move_semantics5.rs"

[[bin]]
name = "07_structs_structs1"
path = "src/exercises/07_structs/structs1.rs"

[[bin]]
name = "07_structs_structs2"
path = "src/exercises/07_structs/structs2.rs"

[[bin]]
name = "07_structs_structs3"
path = "src/exercises/07_structs/structs3.rs"

[[bin]]
name = "08_enums_enums1"
path = "src/exercises/08_enums/enums1.rs"

[[bin]]
name = "08_enums_enums2"
path = "src/exercises/08_enums/enums2.rs"

[[bin]]
name = "08_enums_enums3"
path = "src/exercises/08_enums/enums3.rs"

[[bin]]
name = "09_strings_strings1"
path = "src/exercises/09_strings/strings1.rs"

[[bin]]
name = "09_strings_strings2"
path = "src/exercises/09_strings/strings2.rs"

[[bin]]
name = "09_strings_strings3"
path = "src/exercises/09_strings/strings3.rs"

[[bin]]
name = "09_strings_strings4"
path = "src/exercises/09_strings/strings4.rs"

[dependencies]
thread_local = "1.1"
