[package]
name = "rust_learn"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vec"
path = "src/collections/vec.rs"

[[bin]]
name = "vecdeque"
path = "src/collections/vecdeque.rs"

[[bin]]
name = "linkedlist"
path = "src/collections/linkedlist.rs"

[[bin]]
name = "box_array"
path = "src/collections/box_array.rs"

[[bin]]
name = "btreemap"
path = "src/collections/btreemap.rs"

[[bin]]
name = "hashmap"
path = "src/collections/hashmap.rs"

[[bin]]
name = "hashset"
path = "src/collections/hashset.rs"

[[bin]]
name = "btreeset"
path = "src/collections/btreeset.rs"

[[bin]]
name = "basic_thread"
path = "src/threads/basic.rs"

[[bin]]
name = "thread_local"
path = "src/threads/thread_local.rs"

[[bin]]
name = "thread_sync"
path = "src/threads/sync.rs"

[[bin]]
name = "thread_attributes"
path = "src/threads/attributes.rs"

[[bin]]
name = "thread_advanced"
path = "src/threads/advanced.rs"

[[bin]]
name = "thread_complete"
path = "src/threads/complete.rs"

[[bin]]
name = "edition_2015"
path = "src/edition_features/edition_2015.rs"

[[bin]]
name = "edition_2018"
path = "src/edition_features/edition_2018.rs"

[dependencies]
thread_local = "1.1"
